# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: btg_development

test:
  <<: *default
  database: btg_test

production:
  <<: *default
  database: bridging-app
  host: 138.68.39.185
  port: 54532
  username: <%= ENV['BTG_DATABASE_USERNAME'] %>
  password: <%= ENV['BTG_DATABASE_PASSWORD'] %>
